//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmplitudeCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmplitudeCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="point"/>
 *     &lt;enumeration value="mean"/>
 *     &lt;enumeration value="duration"/>
 *     &lt;enumeration value="period"/>
 *     &lt;enumeration value="integral"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmplitudeCategory")
@XmlEnum
public enum AmplitudeCategory {

    @XmlEnumValue("point")
    POINT("point"),
    @XmlEnumValue("mean")
    MEAN("mean"),
    @XmlEnumValue("duration")
    DURATION("duration"),
    @XmlEnumValue("period")
    PERIOD("period"),
    @XmlEnumValue("integral")
    INTEGRAL("integral"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AmplitudeCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmplitudeCategory fromValue(String v) {
        for (AmplitudeCategory c: AmplitudeCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
