//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmplitudeUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmplitudeUnit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="s"/>
 *     &lt;enumeration value="m/s"/>
 *     &lt;enumeration value="m/(s*s)"/>
 *     &lt;enumeration value="m*s"/>
 *     &lt;enumeration value="dimensionless"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmplitudeUnit")
@XmlEnum
public enum AmplitudeUnit {

    @XmlEnumValue("m")
    METERS("m"),
    @XmlEnumValue("s")
    SECONDS("s"),
    @XmlEnumValue("m/s")
    METERS_PER_SECOND("m/s"),
    @XmlEnumValue("m/(s*s)")
    METERS_PER_SECOND_SQUARED("m/(s*s)"),
    @XmlEnumValue("m*s")
    METER_SECONDS("m*s"),
    @XmlEnumValue("dimensionless")
    DIMENSIONLESS("dimensionless"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AmplitudeUnit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmplitudeUnit fromValue(String v) {
        for (AmplitudeUnit c: AmplitudeUnit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
