//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.quakeml_1_2.helpers.Adapter3;
import org.w3c.dom.Element;


/**
 * <p>Java class for ConfidenceEllipsoid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfidenceEllipsoid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="semiMajorAxisLength" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="semiMinorAxisLength" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="semiIntermediateAxisLength" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="majorAxisPlunge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="majorAxisAzimuth" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="majorAxisRotation" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfidenceEllipsoid", propOrder = {
    "semiMajorAxisLength",
    "semiMinorAxisLength",
    "semiIntermediateAxisLength",
    "majorAxisPlunge",
    "majorAxisAzimuth",
    "majorAxisRotation",
    "anies"
})
public class ConfidenceEllipsoid {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal semiMajorAxisLength;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal semiMinorAxisLength;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal semiIntermediateAxisLength;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal majorAxisPlunge;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal majorAxisAzimuth;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal majorAxisRotation;
    @XmlAnyElement
    protected List<Element> anies;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the semiMajorAxisLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getSemiMajorAxisLength() {
        return semiMajorAxisLength;
    }

    /**
     * Sets the value of the semiMajorAxisLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemiMajorAxisLength(BigDecimal value) {
        this.semiMajorAxisLength = value;
    }

    /**
     * Gets the value of the semiMinorAxisLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getSemiMinorAxisLength() {
        return semiMinorAxisLength;
    }

    /**
     * Sets the value of the semiMinorAxisLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemiMinorAxisLength(BigDecimal value) {
        this.semiMinorAxisLength = value;
    }

    /**
     * Gets the value of the semiIntermediateAxisLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getSemiIntermediateAxisLength() {
        return semiIntermediateAxisLength;
    }

    /**
     * Sets the value of the semiIntermediateAxisLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemiIntermediateAxisLength(BigDecimal value) {
        this.semiIntermediateAxisLength = value;
    }

    /**
     * Gets the value of the majorAxisPlunge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMajorAxisPlunge() {
        return majorAxisPlunge;
    }

    /**
     * Sets the value of the majorAxisPlunge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisPlunge(BigDecimal value) {
        this.majorAxisPlunge = value;
    }

    /**
     * Gets the value of the majorAxisAzimuth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMajorAxisAzimuth() {
        return majorAxisAzimuth;
    }

    /**
     * Sets the value of the majorAxisAzimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisAzimuth(BigDecimal value) {
        this.majorAxisAzimuth = value;
    }

    /**
     * Gets the value of the majorAxisRotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMajorAxisRotation() {
        return majorAxisRotation;
    }

    /**
     * Sets the value of the majorAxisRotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisRotation(BigDecimal value) {
        this.majorAxisRotation = value;
    }

    /**
     * Gets the value of the anies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Element>();
        }
        return this.anies;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
