//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataUsedWaveType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataUsedWaveType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="P waves"/>
 *     &lt;enumeration value="body waves"/>
 *     &lt;enumeration value="surface waves"/>
 *     &lt;enumeration value="mantle waves"/>
 *     &lt;enumeration value="combined"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataUsedWaveType")
@XmlEnum
public enum DataUsedWaveType {

    @XmlEnumValue("P waves")
    P_WAVES("P waves"),
    @XmlEnumValue("body waves")
    BODY_WAVES("body waves"),
    @XmlEnumValue("surface waves")
    SURFACE_WAVES("surface waves"),
    @XmlEnumValue("mantle waves")
    MANTLE_WAVES("mantle waves"),
    @XmlEnumValue("combined")
    COMBINED("combined"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    DataUsedWaveType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataUsedWaveType fromValue(String v) {
        for (DataUsedWaveType c: DataUsedWaveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
