//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvaluationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EvaluationStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="preliminary"/>
 *     &lt;enumeration value="confirmed"/>
 *     &lt;enumeration value="reviewed"/>
 *     &lt;enumeration value="final"/>
 *     &lt;enumeration value="rejected"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EvaluationStatus")
@XmlEnum
public enum EvaluationStatus {

    @XmlEnumValue("preliminary")
    PRELIMINARY("preliminary"),
    @XmlEnumValue("confirmed")
    CONFIRMED("confirmed"),
    @XmlEnumValue("reviewed")
    REVIEWED("reviewed"),
    @XmlEnumValue("final")
    FINAL("final"),
    @XmlEnumValue("rejected")
    REJECTED("rejected");
    private final String value;

    EvaluationStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EvaluationStatus fromValue(String v) {
        for (EvaluationStatus c: EvaluationStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
