//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="not existing"/>
 *     &lt;enumeration value="not reported"/>
 *     &lt;enumeration value="earthquake"/>
 *     &lt;enumeration value="anthropogenic event"/>
 *     &lt;enumeration value="collapse"/>
 *     &lt;enumeration value="cavity collapse"/>
 *     &lt;enumeration value="mine collapse"/>
 *     &lt;enumeration value="building collapse"/>
 *     &lt;enumeration value="explosion"/>
 *     &lt;enumeration value="accidental explosion"/>
 *     &lt;enumeration value="chemical explosion"/>
 *     &lt;enumeration value="controlled explosion"/>
 *     &lt;enumeration value="experimental explosion"/>
 *     &lt;enumeration value="industrial explosion"/>
 *     &lt;enumeration value="mining explosion"/>
 *     &lt;enumeration value="quarry blast"/>
 *     &lt;enumeration value="road cut"/>
 *     &lt;enumeration value="blasting levee"/>
 *     &lt;enumeration value="nuclear explosion"/>
 *     &lt;enumeration value="induced or triggered event"/>
 *     &lt;enumeration value="rock burst"/>
 *     &lt;enumeration value="reservoir loading"/>
 *     &lt;enumeration value="fluid injection"/>
 *     &lt;enumeration value="fluid extraction"/>
 *     &lt;enumeration value="crash"/>
 *     &lt;enumeration value="plane crash"/>
 *     &lt;enumeration value="train crash"/>
 *     &lt;enumeration value="boat crash"/>
 *     &lt;enumeration value="other event"/>
 *     &lt;enumeration value="atmospheric event"/>
 *     &lt;enumeration value="sonic boom"/>
 *     &lt;enumeration value="sonic blast"/>
 *     &lt;enumeration value="acoustic noise"/>
 *     &lt;enumeration value="thunder"/>
 *     &lt;enumeration value="avalanche"/>
 *     &lt;enumeration value="snow avalanche"/>
 *     &lt;enumeration value="debris avalanche"/>
 *     &lt;enumeration value="hydroacoustic event"/>
 *     &lt;enumeration value="ice quake"/>
 *     &lt;enumeration value="slide"/>
 *     &lt;enumeration value="landslide"/>
 *     &lt;enumeration value="rockslide"/>
 *     &lt;enumeration value="meteorite"/>
 *     &lt;enumeration value="volcanic eruption"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventType")
@XmlEnum
public enum EventType {

    @XmlEnumValue("not existing")
    NOT_EXISTING("not existing"),
    @XmlEnumValue("not reported")
    NOT_REPORTED("not reported"),
    @XmlEnumValue("earthquake")
    EARTHQUAKE("earthquake"),
    @XmlEnumValue("anthropogenic event")
    ANTHROPOGENIC_EVENT("anthropogenic event"),
    @XmlEnumValue("collapse")
    COLLAPSE("collapse"),
    @XmlEnumValue("cavity collapse")
    CAVITY_COLLAPSE("cavity collapse"),
    @XmlEnumValue("mine collapse")
    MINE_COLLAPSE("mine collapse"),
    @XmlEnumValue("building collapse")
    BUILDING_COLLAPSE("building collapse"),
    @XmlEnumValue("explosion")
    EXPLOSION("explosion"),
    @XmlEnumValue("accidental explosion")
    ACCIDENTAL_EXPLOSION("accidental explosion"),
    @XmlEnumValue("chemical explosion")
    CHEMICAL_EXPLOSION("chemical explosion"),
    @XmlEnumValue("controlled explosion")
    CONTROLLED_EXPLOSION("controlled explosion"),
    @XmlEnumValue("experimental explosion")
    EXPERIMENTAL_EXPLOSION("experimental explosion"),
    @XmlEnumValue("industrial explosion")
    INDUSTRIAL_EXPLOSION("industrial explosion"),
    @XmlEnumValue("mining explosion")
    MINING_EXPLOSION("mining explosion"),
    @XmlEnumValue("quarry blast")
    QUARRY_BLAST("quarry blast"),
    @XmlEnumValue("road cut")
    ROAD_CUT("road cut"),
    @XmlEnumValue("blasting levee")
    BLASTING_LEVEE("blasting levee"),
    @XmlEnumValue("nuclear explosion")
    NUCLEAR_EXPLOSION("nuclear explosion"),
    @XmlEnumValue("induced or triggered event")
    INDUCED_OR_TRIGGERED_EVENT("induced or triggered event"),
    @XmlEnumValue("rock burst")
    ROCK_BURST("rock burst"),
    @XmlEnumValue("reservoir loading")
    RESERVOIR_LOADING("reservoir loading"),
    @XmlEnumValue("fluid injection")
    FLUID_INJECTION("fluid injection"),
    @XmlEnumValue("fluid extraction")
    FLUID_EXTRACTION("fluid extraction"),
    @XmlEnumValue("crash")
    CRASH("crash"),
    @XmlEnumValue("plane crash")
    PLANE_CRASH("plane crash"),
    @XmlEnumValue("train crash")
    TRAIN_CRASH("train crash"),
    @XmlEnumValue("boat crash")
    BOAT_CRASH("boat crash"),
    @XmlEnumValue("other event")
    OTHER_EVENT("other event"),
    @XmlEnumValue("atmospheric event")
    ATMOSPHERIC_EVENT("atmospheric event"),
    @XmlEnumValue("sonic boom")
    SONIC_BOOM("sonic boom"),
    @XmlEnumValue("sonic blast")
    SONIC_BLAST("sonic blast"),
    @XmlEnumValue("acoustic noise")
    ACOUSTIC_NOISE("acoustic noise"),
    @XmlEnumValue("thunder")
    THUNDER("thunder"),
    @XmlEnumValue("avalanche")
    AVALANCHE("avalanche"),
    @XmlEnumValue("snow avalanche")
    SNOW_AVALANCHE("snow avalanche"),
    @XmlEnumValue("debris avalanche")
    DEBRIS_AVALANCHE("debris avalanche"),
    @XmlEnumValue("hydroacoustic event")
    HYDROACOUSTIC_EVENT("hydroacoustic event"),
    @XmlEnumValue("ice quake")
    ICE_QUAKE("ice quake"),
    @XmlEnumValue("slide")
    SLIDE("slide"),
    @XmlEnumValue("landslide")
    LANDSLIDE("landslide"),
    @XmlEnumValue("rockslide")
    ROCKSLIDE("rockslide"),
    @XmlEnumValue("meteorite")
    METEORITE("meteorite"),
    @XmlEnumValue("volcanic eruption")
    VOLCANIC_ERUPTION("volcanic eruption");
    private final String value;

    EventType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventType fromValue(String v) {
        for (EventType c: EventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
