//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.quakeml_1_2.helpers.Adapter3;
import org.w3c.dom.Element;


/**
 * <p>Java class for FocalMechanism complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FocalMechanism">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="waveformID" type="{http://quakeml.org/xmlns/bed/1.2}WaveformStreamID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://quakeml.org/xmlns/bed/1.2}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="momentTensor" type="{http://quakeml.org/xmlns/bed/1.2}MomentTensor" minOccurs="0"/>
 *         &lt;element name="triggeringOriginID" type="{http://quakeml.org/xmlns/bed/1.2}ResourceReference" minOccurs="0"/>
 *         &lt;element name="nodalPlanes" type="{http://quakeml.org/xmlns/bed/1.2}NodalPlanes" minOccurs="0"/>
 *         &lt;element name="principalAxes" type="{http://quakeml.org/xmlns/bed/1.2}PrincipalAxes" minOccurs="0"/>
 *         &lt;element name="azimuthalGap" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="stationPolarityCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="misfit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="stationDistributionRatio" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="methodID" type="{http://quakeml.org/xmlns/bed/1.2}ResourceReference" minOccurs="0"/>
 *         &lt;element name="evaluationMode" type="{http://quakeml.org/xmlns/bed/1.2}EvaluationMode" minOccurs="0"/>
 *         &lt;element name="evaluationStatus" type="{http://quakeml.org/xmlns/bed/1.2}EvaluationStatus" minOccurs="0"/>
 *         &lt;element name="creationInfo" type="{http://quakeml.org/xmlns/bed/1.2}CreationInfo" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="publicID" use="required" type="{http://quakeml.org/xmlns/bed/1.2}ResourceReference" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FocalMechanism", propOrder = {
    "waveformIDs",
    "comments",
    "momentTensor",
    "triggeringOriginID",
    "nodalPlanes",
    "principalAxes",
    "azimuthalGap",
    "stationPolarityCount",
    "misfit",
    "stationDistributionRatio",
    "methodID",
    "evaluationMode",
    "evaluationStatus",
    "creationInfo",
    "anies"
})
public class FocalMechanism {

    @XmlElement(name = "waveformID")
    protected List<WaveformStreamID> waveformIDs;
    @XmlElement(name = "comment")
    protected List<Comment> comments;
    protected MomentTensor momentTensor;
    protected String triggeringOriginID;
    protected NodalPlanes nodalPlanes;
    protected PrincipalAxes principalAxes;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal azimuthalGap;
    protected Integer stationPolarityCount;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal misfit;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal stationDistributionRatio;
    protected String methodID;
    protected EvaluationMode evaluationMode;
    protected EvaluationStatus evaluationStatus;
    protected CreationInfo creationInfo;
    @XmlAnyElement
    protected List<Element> anies;
    @XmlAttribute(name = "publicID", required = true)
    protected String publicID;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the waveformIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveformIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveformIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaveformStreamID }
     * 
     * 
     */
    public List<WaveformStreamID> getWaveformIDs() {
        if (waveformIDs == null) {
            waveformIDs = new ArrayList<WaveformStreamID>();
        }
        return this.waveformIDs;
    }

    /**
     * Gets the value of the comments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComments() {
        if (comments == null) {
            comments = new ArrayList<Comment>();
        }
        return this.comments;
    }

    /**
     * Gets the value of the momentTensor property.
     * 
     * @return
     *     possible object is
     *     {@link MomentTensor }
     *     
     */
    public MomentTensor getMomentTensor() {
        return momentTensor;
    }

    /**
     * Sets the value of the momentTensor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MomentTensor }
     *     
     */
    public void setMomentTensor(MomentTensor value) {
        this.momentTensor = value;
    }

    /**
     * Gets the value of the triggeringOriginID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggeringOriginID() {
        return triggeringOriginID;
    }

    /**
     * Sets the value of the triggeringOriginID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggeringOriginID(String value) {
        this.triggeringOriginID = value;
    }

    /**
     * Gets the value of the nodalPlanes property.
     * 
     * @return
     *     possible object is
     *     {@link NodalPlanes }
     *     
     */
    public NodalPlanes getNodalPlanes() {
        return nodalPlanes;
    }

    /**
     * Sets the value of the nodalPlanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodalPlanes }
     *     
     */
    public void setNodalPlanes(NodalPlanes value) {
        this.nodalPlanes = value;
    }

    /**
     * Gets the value of the principalAxes property.
     * 
     * @return
     *     possible object is
     *     {@link PrincipalAxes }
     *     
     */
    public PrincipalAxes getPrincipalAxes() {
        return principalAxes;
    }

    /**
     * Sets the value of the principalAxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrincipalAxes }
     *     
     */
    public void setPrincipalAxes(PrincipalAxes value) {
        this.principalAxes = value;
    }

    /**
     * Gets the value of the azimuthalGap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAzimuthalGap() {
        return azimuthalGap;
    }

    /**
     * Sets the value of the azimuthalGap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzimuthalGap(BigDecimal value) {
        this.azimuthalGap = value;
    }

    /**
     * Gets the value of the stationPolarityCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStationPolarityCount() {
        return stationPolarityCount;
    }

    /**
     * Sets the value of the stationPolarityCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStationPolarityCount(Integer value) {
        this.stationPolarityCount = value;
    }

    /**
     * Gets the value of the misfit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMisfit() {
        return misfit;
    }

    /**
     * Sets the value of the misfit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisfit(BigDecimal value) {
        this.misfit = value;
    }

    /**
     * Gets the value of the stationDistributionRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getStationDistributionRatio() {
        return stationDistributionRatio;
    }

    /**
     * Sets the value of the stationDistributionRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationDistributionRatio(BigDecimal value) {
        this.stationDistributionRatio = value;
    }

    /**
     * Gets the value of the methodID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodID() {
        return methodID;
    }

    /**
     * Sets the value of the methodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodID(String value) {
        this.methodID = value;
    }

    /**
     * Gets the value of the evaluationMode property.
     * 
     * @return
     *     possible object is
     *     {@link EvaluationMode }
     *     
     */
    public EvaluationMode getEvaluationMode() {
        return evaluationMode;
    }

    /**
     * Sets the value of the evaluationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvaluationMode }
     *     
     */
    public void setEvaluationMode(EvaluationMode value) {
        this.evaluationMode = value;
    }

    /**
     * Gets the value of the evaluationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EvaluationStatus }
     *     
     */
    public EvaluationStatus getEvaluationStatus() {
        return evaluationStatus;
    }

    /**
     * Sets the value of the evaluationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvaluationStatus }
     *     
     */
    public void setEvaluationStatus(EvaluationStatus value) {
        this.evaluationStatus = value;
    }

    /**
     * Gets the value of the creationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfo }
     *     
     */
    public CreationInfo getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfo }
     *     
     */
    public void setCreationInfo(CreationInfo value) {
        this.creationInfo = value;
    }

    /**
     * Gets the value of the anies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Element>();
        }
        return this.anies;
    }

    /**
     * Gets the value of the publicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicID() {
        return publicID;
    }

    /**
     * Sets the value of the publicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicID(String value) {
        this.publicID = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
