//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MTInversionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MTInversionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="general"/>
 *     &lt;enumeration value="zero trace"/>
 *     &lt;enumeration value="double couple"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MTInversionType")
@XmlEnum
public enum MTInversionType {

    @XmlEnumValue("general")
    GENERAL("general"),
    @XmlEnumValue("zero trace")
    ZERO_TRACE("zero trace"),
    @XmlEnumValue("double couple")
    DOUBLE_COUPLE("double couple");
    private final String value;

    MTInversionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MTInversionType fromValue(String v) {
        for (MTInversionType c: MTInversionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
