//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for NodalPlanes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodalPlanes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodalPlane1" type="{http://quakeml.org/xmlns/bed/1.2}NodalPlane" minOccurs="0"/>
 *         &lt;element name="nodalPlane2" type="{http://quakeml.org/xmlns/bed/1.2}NodalPlane" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="preferredPlane" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodalPlanes", propOrder = {
    "nodalPlane1",
    "nodalPlane2",
    "anies"
})
public class NodalPlanes {

    protected NodalPlane nodalPlane1;
    protected NodalPlane nodalPlane2;
    @XmlAnyElement
    protected List<Element> anies;
    @XmlAttribute(name = "preferredPlane")
    protected BigInteger preferredPlane;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the nodalPlane1 property.
     * 
     * @return
     *     possible object is
     *     {@link NodalPlane }
     *     
     */
    public NodalPlane getNodalPlane1() {
        return nodalPlane1;
    }

    /**
     * Sets the value of the nodalPlane1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodalPlane }
     *     
     */
    public void setNodalPlane1(NodalPlane value) {
        this.nodalPlane1 = value;
    }

    /**
     * Gets the value of the nodalPlane2 property.
     * 
     * @return
     *     possible object is
     *     {@link NodalPlane }
     *     
     */
    public NodalPlane getNodalPlane2() {
        return nodalPlane2;
    }

    /**
     * Sets the value of the nodalPlane2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodalPlane }
     *     
     */
    public void setNodalPlane2(NodalPlane value) {
        this.nodalPlane2 = value;
    }

    /**
     * Gets the value of the anies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Element>();
        }
        return this.anies;
    }

    /**
     * Gets the value of the preferredPlane property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPreferredPlane() {
        return preferredPlane;
    }

    /**
     * Sets the value of the preferredPlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPreferredPlane(BigInteger value) {
        this.preferredPlane = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
