//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.quakeml_1_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.quakeml_1_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventParameters }
     * 
     */
    public EventParameters createEventParameters() {
        return new EventParameters();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link CreationInfo }
     * 
     */
    public CreationInfo createCreationInfo() {
        return new CreationInfo();
    }

    /**
     * Create an instance of {@link Tensor }
     * 
     */
    public Tensor createTensor() {
        return new Tensor();
    }

    /**
     * Create an instance of {@link Magnitude }
     * 
     */
    public Magnitude createMagnitude() {
        return new Magnitude();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link WaveformStreamID }
     * 
     */
    public WaveformStreamID createWaveformStreamID() {
        return new WaveformStreamID();
    }

    /**
     * Create an instance of {@link EventDescription }
     * 
     */
    public EventDescription createEventDescription() {
        return new EventDescription();
    }

    /**
     * Create an instance of {@link Pick }
     * 
     */
    public Pick createPick() {
        return new Pick();
    }

    /**
     * Create an instance of {@link OriginUncertainty }
     * 
     */
    public OriginUncertainty createOriginUncertainty() {
        return new OriginUncertainty();
    }

    /**
     * Create an instance of {@link Arrival }
     * 
     */
    public Arrival createArrival() {
        return new Arrival();
    }

    /**
     * Create an instance of {@link TimeQuantity }
     * 
     */
    public TimeQuantity createTimeQuantity() {
        return new TimeQuantity();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link Amplitude }
     * 
     */
    public Amplitude createAmplitude() {
        return new Amplitude();
    }

    /**
     * Create an instance of {@link StationMagnitudeContribution }
     * 
     */
    public StationMagnitudeContribution createStationMagnitudeContribution() {
        return new StationMagnitudeContribution();
    }

    /**
     * Create an instance of {@link CompositeTime }
     * 
     */
    public CompositeTime createCompositeTime() {
        return new CompositeTime();
    }

    /**
     * Create an instance of {@link OriginQuality }
     * 
     */
    public OriginQuality createOriginQuality() {
        return new OriginQuality();
    }

    /**
     * Create an instance of {@link SourceTimeFunction }
     * 
     */
    public SourceTimeFunction createSourceTimeFunction() {
        return new SourceTimeFunction();
    }

    /**
     * Create an instance of {@link DataUsed }
     * 
     */
    public DataUsed createDataUsed() {
        return new DataUsed();
    }

    /**
     * Create an instance of {@link Phase }
     * 
     */
    public Phase createPhase() {
        return new Phase();
    }

    /**
     * Create an instance of {@link IntegerQuantity }
     * 
     */
    public IntegerQuantity createIntegerQuantity() {
        return new IntegerQuantity();
    }

    /**
     * Create an instance of {@link NodalPlanes }
     * 
     */
    public NodalPlanes createNodalPlanes() {
        return new NodalPlanes();
    }

    /**
     * Create an instance of {@link PrincipalAxes }
     * 
     */
    public PrincipalAxes createPrincipalAxes() {
        return new PrincipalAxes();
    }

    /**
     * Create an instance of {@link TimeWindow }
     * 
     */
    public TimeWindow createTimeWindow() {
        return new TimeWindow();
    }

    /**
     * Create an instance of {@link RealQuantity }
     * 
     */
    public RealQuantity createRealQuantity() {
        return new RealQuantity();
    }

    /**
     * Create an instance of {@link StationMagnitude }
     * 
     */
    public StationMagnitude createStationMagnitude() {
        return new StationMagnitude();
    }

    /**
     * Create an instance of {@link NodalPlane }
     * 
     */
    public NodalPlane createNodalPlane() {
        return new NodalPlane();
    }

    /**
     * Create an instance of {@link MomentTensor }
     * 
     */
    public MomentTensor createMomentTensor() {
        return new MomentTensor();
    }

    /**
     * Create an instance of {@link ConfidenceEllipsoid }
     * 
     */
    public ConfidenceEllipsoid createConfidenceEllipsoid() {
        return new ConfidenceEllipsoid();
    }

    /**
     * Create an instance of {@link FocalMechanism }
     * 
     */
    public FocalMechanism createFocalMechanism() {
        return new FocalMechanism();
    }

    /**
     * Create an instance of {@link Quakeml }
     * 
     */
    public Quakeml createQuakeml() {
        return new Quakeml();
    }

}
