//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginUncertaintyDescription.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OriginUncertaintyDescription">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="horizontal uncertainty"/>
 *     &lt;enumeration value="uncertainty ellipse"/>
 *     &lt;enumeration value="confidence ellipsoid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OriginUncertaintyDescription")
@XmlEnum
public enum OriginUncertaintyDescription {

    @XmlEnumValue("horizontal uncertainty")
    HORIZONTAL_UNCERTAINTY("horizontal uncertainty"),
    @XmlEnumValue("uncertainty ellipse")
    UNCERTAINTY_ELLIPSE("uncertainty ellipse"),
    @XmlEnumValue("confidence ellipsoid")
    CONFIDENCE_ELLIPSOID("confidence ellipsoid");
    private final String value;

    OriginUncertaintyDescription(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OriginUncertaintyDescription fromValue(String v) {
        for (OriginUncertaintyDescription c: OriginUncertaintyDescription.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
