//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OriginType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="hypocenter"/>
 *     &lt;enumeration value="centroid"/>
 *     &lt;enumeration value="amplitude"/>
 *     &lt;enumeration value="macroseismic"/>
 *     &lt;enumeration value="rupture start"/>
 *     &lt;enumeration value="rupture end"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OriginType")
@XmlEnum
public enum OriginType {

    @XmlEnumValue("hypocenter")
    HYPOCENTER("hypocenter"),
    @XmlEnumValue("centroid")
    CENTROID("centroid"),
    @XmlEnumValue("amplitude")
    AMPLITUDE("amplitude"),
    @XmlEnumValue("macroseismic")
    MACROSEISMIC("macroseismic"),
    @XmlEnumValue("rupture start")
    RUPTURE_START("rupture start"),
    @XmlEnumValue("rupture end")
    RUPTURE_END("rupture end");
    private final String value;

    OriginType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OriginType fromValue(String v) {
        for (OriginType c: OriginType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
