//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.quakeml_1_2.helpers.Adapter3;
import org.w3c.dom.Element;


/**
 * <p>Java class for OriginUncertainty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginUncertainty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="horizontalUncertainty" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="minHorizontalUncertainty" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="maxHorizontalUncertainty" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="azimuthMaxHorizontalUncertainty" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="confidenceEllipsoid" type="{http://quakeml.org/xmlns/bed/1.2}ConfidenceEllipsoid" minOccurs="0"/>
 *         &lt;element name="preferredDescription" type="{http://quakeml.org/xmlns/bed/1.2}OriginUncertaintyDescription" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginUncertainty", propOrder = {
    "horizontalUncertainty",
    "minHorizontalUncertainty",
    "maxHorizontalUncertainty",
    "azimuthMaxHorizontalUncertainty",
    "confidenceEllipsoid",
    "preferredDescription",
    "anies"
})
public class OriginUncertainty {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal horizontalUncertainty;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal minHorizontalUncertainty;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal maxHorizontalUncertainty;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "double")
    protected BigDecimal azimuthMaxHorizontalUncertainty;
    protected ConfidenceEllipsoid confidenceEllipsoid;
    protected OriginUncertaintyDescription preferredDescription;
    @XmlAnyElement
    protected List<Element> anies;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the horizontalUncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getHorizontalUncertainty() {
        return horizontalUncertainty;
    }

    /**
     * Sets the value of the horizontalUncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalUncertainty(BigDecimal value) {
        this.horizontalUncertainty = value;
    }

    /**
     * Gets the value of the minHorizontalUncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMinHorizontalUncertainty() {
        return minHorizontalUncertainty;
    }

    /**
     * Sets the value of the minHorizontalUncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinHorizontalUncertainty(BigDecimal value) {
        this.minHorizontalUncertainty = value;
    }

    /**
     * Gets the value of the maxHorizontalUncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getMaxHorizontalUncertainty() {
        return maxHorizontalUncertainty;
    }

    /**
     * Sets the value of the maxHorizontalUncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxHorizontalUncertainty(BigDecimal value) {
        this.maxHorizontalUncertainty = value;
    }

    /**
     * Gets the value of the azimuthMaxHorizontalUncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAzimuthMaxHorizontalUncertainty() {
        return azimuthMaxHorizontalUncertainty;
    }

    /**
     * Sets the value of the azimuthMaxHorizontalUncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzimuthMaxHorizontalUncertainty(BigDecimal value) {
        this.azimuthMaxHorizontalUncertainty = value;
    }

    /**
     * Gets the value of the confidenceEllipsoid property.
     * 
     * @return
     *     possible object is
     *     {@link ConfidenceEllipsoid }
     *     
     */
    public ConfidenceEllipsoid getConfidenceEllipsoid() {
        return confidenceEllipsoid;
    }

    /**
     * Sets the value of the confidenceEllipsoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfidenceEllipsoid }
     *     
     */
    public void setConfidenceEllipsoid(ConfidenceEllipsoid value) {
        this.confidenceEllipsoid = value;
    }

    /**
     * Gets the value of the preferredDescription property.
     * 
     * @return
     *     possible object is
     *     {@link OriginUncertaintyDescription }
     *     
     */
    public OriginUncertaintyDescription getPreferredDescription() {
        return preferredDescription;
    }

    /**
     * Sets the value of the preferredDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginUncertaintyDescription }
     *     
     */
    public void setPreferredDescription(OriginUncertaintyDescription value) {
        this.preferredDescription = value;
    }

    /**
     * Gets the value of the anies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Element>();
        }
        return this.anies;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
