//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 02:22:50 PM PDT 
//


package edu.iris.quake.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PickOnset.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PickOnset">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="emergent"/>
 *     &lt;enumeration value="impulsive"/>
 *     &lt;enumeration value="questionable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PickOnset")
@XmlEnum
public enum PickOnset {

    @XmlEnumValue("emergent")
    EMERGENT("emergent"),
    @XmlEnumValue("impulsive")
    IMPULSIVE("impulsive"),
    @XmlEnumValue("questionable")
    QUESTIONABLE("questionable");
    private final String value;

    PickOnset(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PickOnset fromValue(String v) {
        for (PickOnset c: PickOnset.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
