//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 01:45:01 PM PDT 
//


package org.quakeml_1_2.helpers;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (org.quakeml_1_2.helpers.QuakemlDateParser.getDate(value));
    }

    public String marshal(Date value) {
        return (org.quakeml_1_2.helpers.QuakemlDateParser.formatDate(value));
    }

}
